import { Work_Sans, Fraunces } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const workSans = Work_Sans({
  weight: "variable",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  weight: "variable",
  subsets: ["latin"],
});

export const metadata = {
  title: "The Female Gaze",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${workSans.className} ${fraunces.variable}`}>
        <Header />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
